import os
import logging
from typing import Dict, Any
from ..models import QueryRequest, QueryResponse
from ..demo_data import demo_query_response

logger = logging.getLogger(__name__)

class QueryService:
    def __init__(self):
        self.pipeline = None
        self.is_ready = False
        
        try:
            # Check for API key before trying to initialize pipeline
            groq_key = os.getenv("GROQ_API_KEY")
            
            # Check if index exists
            index_path = os.path.join("data", "index")
            has_index = os.path.exists(index_path) and len(os.listdir(index_path)) > 0
            
            if groq_key and has_index:
                from ..pipeline.rag_pipeline import IPRAGPipeline
                logger.info("Initializing IPRAGPipeline...")
                self.pipeline = IPRAGPipeline()
                self.is_ready = True
                logger.info("IPRAGPipeline initialized successfully.")
            else:
                logger.warning(f"Pipeline not initialized. GROQ_API_KEY present: {bool(groq_key)}, Index present: {has_index}. Using demo mode.")
        except Exception as e:
            logger.error(f"Failed to initialize pipeline: {e}")
            self.is_ready = False

    def process_query(self, request: QueryRequest) -> QueryResponse:
        if not self.is_ready or not self.pipeline:
            logger.info("Using demo response for query.")
            return demo_query_response
            
        try:
            # Use real pipeline
            logger.info(f"Processing query via pipeline: {request.question}")
            result = self.pipeline.query(request.question)
            
            # Map pipeline result to QueryResponse
            # Pipeline returns dict with: answer, confidence_score, retrieved_evidence
            evidence_items = []
            if "retrieved_evidence" in result:
                for idx, ev in enumerate(result["retrieved_evidence"]):
                    # Handle varying structure of evidence
                    from ..models import EvidenceItem, SourceItem
                    
                    # Assuming ev is Document object or dict
                    content = getattr(ev, 'page_content', str(ev))
                    metadata = getattr(ev, 'metadata', {})
                    
                    source = SourceItem(
                        document_name=metadata.get('source', 'Unknown Document'),
                        page=str(metadata.get('page', '')),
                        content=content[:200] + "..."
                    )
                    
                    evidence_items.append(EvidenceItem(
                        id=f"ev_{idx}",
                        title=f"Evidence {idx+1}",
                        summary=content[:100] + "...",
                        source=source,
                        relevance_score=0.8
                    ))
            
            return QueryResponse(
                answer=result.get("answer", "No answer generated."),
                confidence=result.get("confidence_score", 0.0),
                evidence=evidence_items,
                domains=["General IP"],
                risks=[],
                actions=[],
                citations=[],
                abstained=False,
                disclaimer="This information is generated by AI and is for general guidance only. It does not constitute legal advice."
            )
            
        except Exception as e:
            logger.error(f"Error processing query: {e}")
            return demo_query_response

query_service = QueryService()
