from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime

class QueryRequest(BaseModel):
    question: str
    mode: str = 'quick'
    language: str = 'en'

class SourceItem(BaseModel):
    document_name: str
    authority: Optional[str] = None
    jurisdiction: Optional[str] = None
    section: Optional[str] = None
    page: Optional[str] = None
    version: Optional[str] = None
    effective_date: Optional[str] = None
    source_url: Optional[str] = None
    content: Optional[str] = None

class CitationItem(BaseModel):
    text: str
    source_id: str

class EvidenceItem(BaseModel):
    id: str
    title: str
    summary: str
    source: SourceItem
    relevance_score: float

class QueryResponse(BaseModel):
    answer: str
    confidence: float
    evidence: List[EvidenceItem] = []
    domains: List[str] = []
    primary_domain: Optional[str] = None
    risks: List[str] = []
    actions: List[str] = []
    citations: List[CitationItem] = []
    citation_verified: bool = True
    abstained: bool = False
    disclaimer: str = "This information is generated by AI and is for general guidance only. It does not constitute legal advice."

class GraphNode(BaseModel):
    id: str
    label: str
    type: str

class GraphEdge(BaseModel):
    source: str
    target: str
    relation: str

class EvidenceGraphResponse(BaseModel):
    nodes: List[GraphNode]
    edges: List[GraphEdge]

class RoadmapStep(BaseModel):
    id: str
    title: str
    description: str
    status: str = "pending"
    duration: Optional[str] = None

class ComplianceRoadmapResponse(BaseModel):
    steps: List[RoadmapStep]

class InvestigationSummary(BaseModel):
    id: str
    query: str
    timestamp: datetime
    domain: str
    status: str

class InvestigationDetail(InvestigationSummary):
    response: QueryResponse
    graph: EvidenceGraphResponse
    roadmap: ComplianceRoadmapResponse

class DocumentInfo(BaseModel):
    id: str
    filename: str
    upload_date: str
    status: str
    size: int
    pages: Optional[int] = 0
    chunks: Optional[int] = 0

class DocumentUploadResponse(BaseModel):
    status: str
    message: str
    document_id: str
    filename: Optional[str] = None
    size: Optional[int] = None
    pages: Optional[int] = None
    chunks: Optional[int] = None

class DashboardStats(BaseModel):
    total_investigations: int
    active_cases: int
    documents_indexed: int
    risk_alerts: int
    recent_activity: List[Dict[str, Any]]

class HealthResponse(BaseModel):
    status: str
    mode: str
    version: str
    pipeline_ready: bool

class SuggestedAction(BaseModel):
    label: str
    target_screen: str  # "investigate", "upload", "roadmap", "graph", "evidence"
    payload: Optional[str] = None

class ChatMessage(BaseModel):
    id: str
    sender: str  # "user" or "assistant"
    text: str
    timestamp: str
    actions: List[SuggestedAction] = []
    domain: Optional[str] = None
    domains: List[str] = []

class ChatMessageRequest(BaseModel):
    message: str
    history: List[ChatMessage] = []
    language: str = "en"

class ChatResponse(BaseModel):
    reply: str
    suggested_actions: List[SuggestedAction] = []
    references: List[str] = []
    domain: Optional[str] = None
    domains: List[str] = []

class PatentRecord(BaseModel):
    patent_number: str
    title: str
    applicant: str
    status: str
    filing_date: Optional[str] = None
    jurisdiction: Optional[str] = "India"
    ipc_class: Optional[str] = None
    abstract: Optional[str] = None

class BotanicalInfo(BaseModel):
    name: str
    scientific_name: str
    traditional_uses: str
    classical_texts: str
    sec_3p_risk: str

class PriorArtSearchRequest(BaseModel):
    query: str

class PriorArtSearchResponse(BaseModel):
    query: str
    total_found: int
    detected_botanicals: List[BotanicalInfo] = []
    patents: List[PatentRecord] = []
    patentability_barriers: List[Dict[str, str]] = []
    conclusion_status: str = "Search completed"
    disclaimer: str = "This patent search is preliminary and for guidance only. It does not constitute formal legal certification."
