"""
IP-SAKTI SAHAYAK
Safe Abstention Engine
======================
Enforces responsible AI boundaries. Safely abstains and refuses to guess
when authoritative legal evidence is absent, contradictory, or when queries
fall outside the scope of Intellectual Property and Traditional Knowledge.
"""

import re
from typing import Dict, Any, List, Optional
from config import Config


class SafeAbstentionEngine:
    """Detects when to safely abstain rather than generate hallucinated legal claims."""

    OUT_OF_SCOPE_PATTERNS = [
        r"price of \w+ in \d{4}",
        r"predict (?:the )?future",
        r"stock market",
        r"cryptocurrency",
        r"who will win",
        r"recipe for (?:cake|pasta|pizza)",
        r"write (?:a )?poem",
        r"tell me a joke"
    ]

    def check_out_of_scope(self, query: str) -> Optional[str]:
        """Check if query is completely outside IP/Traditional Knowledge scope."""
        text_lower = query.lower()
        for pattern in self.OUT_OF_SCOPE_PATTERNS:
            if re.search(pattern, text_lower):
                return "The query falls outside the domain of Intellectual Property, Ayurveda, Traditional Knowledge, and Regulatory Law."
        return None

    def evaluate_abstention(
        self,
        query: str,
        evidence_chunks: List[Dict[str, Any]],
        confidence_score: float
    ) -> Dict[str, Any]:
        """
        Determine if the system must safely abstain.
        """
        # 1. Out-of-scope check
        out_of_scope_reason = self.check_out_of_scope(query)
        if out_of_scope_reason:
            return {
                "should_abstain": True,
                "reason": out_of_scope_reason,
                "abstention_response": self._generate_abstention_message(out_of_scope_reason)
            }

        # 2. Empty evidence check
        if not evidence_chunks:
            reason = "No authoritative legal sources, acts, or gazette notifications were found in the knowledge repository."
            return {
                "should_abstain": True,
                "reason": reason,
                "abstention_response": self._generate_abstention_message(reason)
            }

        # 3. Sub-threshold confidence check
        if confidence_score < Config.ABSTENTION_THRESHOLD:
            reason = f"The retrieved legal evidence returned a confidence score of {int(confidence_score * 100)}%, which is below the safe threshold of {int(Config.ABSTENTION_THRESHOLD * 100)}%."
            return {
                "should_abstain": True,
                "reason": reason,
                "abstention_response": self._generate_abstention_message(reason)
            }

        return {
            "should_abstain": False,
            "reason": None,
            "abstention_response": None
        }

    def _generate_abstention_message(self, reason: str) -> str:
        """Format an authoritative and polite safe abstention response."""
        return f"""### DIRECT ANSWER
I could not find sufficient authoritative evidence in the official legal and regulatory sources to answer this question reliably.

### SAFETY NOTICE & REASON
{reason}

### RECOMMENDATION
- For inquiries regarding **Indian Patents, Trademarks, or Designs**, consult the official [IP India Portal](https://ipindia.gov.in) or reference The Patents Act, 1970.
- For matters involving **Ayurvedic formulations and Traditional Knowledge**, verify records within the [Traditional Knowledge Digital Library (TKDL)](https://www.tkdl.res.in) or the Ministry of Ayush.
- For **Biological Diversity and Access & Benefit Sharing (ABS)** clearances, refer to the [National Biodiversity Authority](https://nbaindia.org) and Section 6 of the Biological Diversity Act, 2002.

### STATUTORY DISCLAIMER
This response was generated by IP-SAKTI Sahayak's safe abstention protocol to prevent hallucination of non-existent legal provisions or citations.
"""


# Global singleton instance
abstention_engine = SafeAbstentionEngine()
