
"""
=====================================================
IP-SAKTI SAHAYAK
Configuration File
=====================================================
"""

import os
from pathlib import Path
from dotenv import load_dotenv


# =====================================================
# GROQ / LLM CONFIGURATION
# =====================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]


def load_environment() -> None:
    """Load supported .env files independent of the launch directory."""
    for env_path in (PROJECT_ROOT / "backend" / ".env", PROJECT_ROOT / ".env"):
        load_dotenv(env_path, override=False)


load_environment()
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

if not GROQ_API_KEY:
    # Do not crash on import; allow graceful fallback
    pass



# LLM model used for generating grounded responses
MODEL_NAME = os.getenv("MODEL_NAME", "qwen/qwen3.8-27b")


# Lower temperature is preferred for
# legal and regulatory information
TEMPERATURE = 0.1


# Maximum number of tokens generated by the LLM (optimized for Groq OTPM limits)
MAX_TOKENS = 750



# =====================================================
# EMBEDDING CONFIGURATION
# =====================================================

# Multilingual embedding model
# Useful for English, Hindi, Odia and other languages
EMBEDDING_MODEL = "BAAI/bge-m3"


# =====================================================
# DOCUMENT CONFIGURATION
# =====================================================

# Directory containing original source documents
RAW_DATA_DIR = "data/raw"


# Directory containing processed document data
PROCESSED_DATA_DIR = "data/processed"


# Directory containing vector database/index files
VECTOR_DB_DIR = "data/index"


# Supported document formats
SUPPORTED_DOCUMENT_FORMATS = [
    ".pdf",
    ".txt"
]


# =====================================================
# TEXT CHUNKING CONFIGURATION
# =====================================================

# Maximum size of a document chunk
CHUNK_SIZE = 800


# Number of characters shared between
# consecutive chunks
CHUNK_OVERLAP = 150


# =====================================================
# RETRIEVAL CONFIGURATION
# =====================================================

# Number of chunks retrieved from the vector database
TOP_K = 5


# Minimum similarity threshold for retrieved evidence
# This will later be used for safe abstention
SIMILARITY_THRESHOLD = 0.50


# =====================================================
# RAG CONFIGURATION
# =====================================================

# Maximum amount of retrieved context sent to the LLM
MAX_CONTEXT_LENGTH = 8000


# Enable source-grounded responses
ENABLE_SOURCE_GROUNDING = True


# Require citations in generated responses
REQUIRE_CITATIONS = True


# =====================================================
# JURISDICTION CONFIGURATION
# =====================================================

# Default jurisdiction for the MVP
DEFAULT_JURISDICTION = "India"


# Supported jurisdictions in the initial version
SUPPORTED_JURISDICTIONS = [
    "India",
    "International"
]


# =====================================================
# KNOWLEDGE DOMAIN CONFIGURATION
# =====================================================

# Initial domains supported by the RAG system
SUPPORTED_DOMAINS = [
    "Patents",
    "Trademarks",
    "Copyright",
    "Geographical Indications",
    "Designs",
    "Ayurveda",
    "Traditional Knowledge",
    "Biodiversity",
    "Access and Benefit Sharing",
    "International IP"
]


# =====================================================
# SOURCE CONFIGURATION
# =====================================================

# Only authoritative sources should be used
# for the core knowledge corpus
SOURCE_TYPES = [
    "Government",
    "Statute",
    "Regulation",
    "Treaty",
    "Official Guidance",
    "Official Registry",
    "Pharmacopoeial Standard",
    "Case Law"
]


# =====================================================
# SAFETY CONFIGURATION
# =====================================================

# Enable safe abstention when sufficient evidence
# cannot be found
ENABLE_SAFE_ABSTENTION = True


# Minimum number of retrieved evidence chunks
# required before attempting an answer
MINIMUM_EVIDENCE_COUNT = 1


# Disclaimer shown with legal/regulatory guidance
LEGAL_DISCLAIMER = (
    "This information is provided for informational and research "
    "purposes only and does not constitute legal advice."
)


# =====================================================
# CITATION CONFIGURATION
# =====================================================

# Metadata fields that should be preserved for citations
CITATION_METADATA_FIELDS = [
    "document_name",
    "document_type",
    "authority",
    "jurisdiction",
    "section",
    "page",
    "source_url",
    "version",
    "effective_date"
]


# =====================================================
# DIRECTORY SETUP
# =====================================================

# Create required directories automatically
os.makedirs(RAW_DATA_DIR, exist_ok=True)

os.makedirs(PROCESSED_DATA_DIR, exist_ok=True)

os.makedirs(VECTOR_DB_DIR, exist_ok=True)
