package com.ipsakti.sahayak.data.model

import com.google.gson.annotations.SerializedName

data class QueryRequest(
    @SerializedName("question") val question: String,
    @SerializedName("mode") val mode: String = "quick",
    @SerializedName("language") val language: String = "en",
    @SerializedName("persona") val persona: String = "startup"
)

data class SourceItem(
    @SerializedName("document_name") val documentName: String = "",
    @SerializedName("authority") val authority: String? = null,
    @SerializedName("jurisdiction") val jurisdiction: String? = null,
    @SerializedName("section") val section: String? = null,
    @SerializedName("page") val page: String? = null,
    @SerializedName("version") val version: String? = null,
    @SerializedName("effective_date") val effectiveDate: String? = null,
    @SerializedName("source_url") val sourceUrl: String? = null,
    @SerializedName("content") val content: String? = null
)

data class CitationItem(
    @SerializedName("text") val text: String = "",
    @SerializedName("source_id") val sourceId: String = ""
)

data class EvidenceItem(
    @SerializedName("id") val id: String = "",
    @SerializedName("title") val title: String = "",
    @SerializedName("summary") val summary: String = "",
    @SerializedName("source") val source: SourceItem = SourceItem(),
    @SerializedName("relevance_score") val relevanceScore: Float = 0f
)

data class QueryResponse(
    @SerializedName("answer") val answer: String = "",
    @SerializedName("confidence") val confidence: Float = 0f,
    @SerializedName("evidence") val evidence: List<EvidenceItem> = emptyList(),
    @SerializedName("domains") val domains: List<String> = emptyList(),
    @SerializedName("primary_domain") val primaryDomain: String? = null,
    @SerializedName("risks") val risks: List<String> = emptyList(),
    @SerializedName("actions") val actions: List<String> = emptyList(),
    @SerializedName("citations") val citations: List<CitationItem> = emptyList(),
    @SerializedName("citation_verified") val citationVerified: Boolean = true,
    @SerializedName("abstained") val abstained: Boolean = false,
    @SerializedName("disclaimer") val disclaimer: String = "This information is generated by AI and is for general guidance only. It does not constitute legal advice."
)

data class GraphNode(
    @SerializedName("id") val id: String = "",
    @SerializedName("label") val label: String = "",
    @SerializedName("type") val type: String = ""
)

data class GraphEdge(
    @SerializedName("source") val source: String = "",
    @SerializedName("target") val target: String = "",
    @SerializedName("relation") val relation: String = ""
)

data class EvidenceGraphResponse(
    @SerializedName("nodes") val nodes: List<GraphNode> = emptyList(),
    @SerializedName("edges") val edges: List<GraphEdge> = emptyList()
)

data class RoadmapStep(
    @SerializedName("id") val id: String = "",
    @SerializedName("title") val title: String = "",
    @SerializedName("description") val description: String = "",
    @SerializedName("status") val status: String = "pending",
    @SerializedName("duration") val duration: String? = null
)

data class ComplianceRoadmapResponse(
    @SerializedName("steps") val steps: List<RoadmapStep> = emptyList()
)

data class InvestigationSummary(
    @SerializedName("id") val id: String = "",
    @SerializedName("query") val query: String = "",
    @SerializedName("timestamp") val timestamp: String = "",
    @SerializedName("domain") val domain: String = "",
    @SerializedName("status") val status: String = ""
)

data class InvestigationDetail(
    @SerializedName("id") val id: String = "",
    @SerializedName("query") val query: String = "",
    @SerializedName("timestamp") val timestamp: String = "",
    @SerializedName("domain") val domain: String = "",
    @SerializedName("status") val status: String = "",
    @SerializedName("response") val response: QueryResponse = QueryResponse(),
    @SerializedName("graph") val graph: EvidenceGraphResponse = EvidenceGraphResponse(),
    @SerializedName("roadmap") val roadmap: ComplianceRoadmapResponse = ComplianceRoadmapResponse()
)

data class DashboardStats(
    @SerializedName("total_investigations") val totalInvestigations: Int = 0,
    @SerializedName("active_cases") val activeCases: Int = 0,
    @SerializedName("documents_indexed") val documentsIndexed: Int = 0,
    @SerializedName("risk_alerts") val riskAlerts: Int = 0,
    @SerializedName("recent_activity") val recentActivity: List<Map<String, Any>> = emptyList()
)

data class DocumentUploadResponse(
    @SerializedName("status") val status: String = "",
    @SerializedName("message") val message: String = "",
    @SerializedName("document_id") val documentId: String = "",
    @SerializedName("filename") val filename: String? = null,
    @SerializedName("size") val size: Long? = null,
    @SerializedName("pages") val pages: Int? = null,
    @SerializedName("chunks") val chunks: Int? = null
)

data class DocumentInfo(
    @SerializedName("id") val id: String = "",
    @SerializedName("filename") val filename: String = "",
    @SerializedName("upload_date") val uploadDate: String = "",
    @SerializedName("status") val status: String = "Indexed",
    @SerializedName("size") val size: Long = 0L,
    @SerializedName("pages") val pages: Int = 0,
    @SerializedName("chunks") val chunks: Int = 0
)

data class HealthResponse(
    @SerializedName("status") val status: String = "ok",
    @SerializedName("mode") val mode: String = "demo",
    @SerializedName("version") val version: String = "1.0.0",
    @SerializedName("pipeline_ready") val pipelineReady: Boolean = false
)

data class SuggestedAction(
    @SerializedName("label") val label: String = "",
    @SerializedName("target_screen") val targetScreen: String = "",
    @SerializedName("payload") val payload: String? = null
)

data class ChatMessage(
    @SerializedName("id") val id: String = "",
    @SerializedName("sender") val sender: String = "assistant", // "user" or "assistant"
    @SerializedName("text") val text: String = "",
    @SerializedName("timestamp") val timestamp: String = "",
    @SerializedName("actions") val actions: List<SuggestedAction> = emptyList(),
    @SerializedName("domain") val domain: String? = null,
    @SerializedName("domains") val domains: List<String> = emptyList()
)

data class ChatMessageRequest(
    @SerializedName("message") val message: String,
    @SerializedName("history") val history: List<ChatMessage> = emptyList(),
    @SerializedName("language") val language: String = "en",
    @SerializedName("persona") val persona: String = "startup"
)

data class ChatResponse(
    @SerializedName("reply") val reply: String = "",
    @SerializedName("suggested_actions") val suggestedActions: List<SuggestedAction> = emptyList(),
    @SerializedName("references") val references: List<String> = emptyList(),
    @SerializedName("domain") val domain: String? = null,
    @SerializedName("domains") val domains: List<String> = emptyList()
)

data class PatentRecord(
    @SerializedName("patent_number") val patentNumber: String = "",
    @SerializedName("title") val title: String = "",
    @SerializedName("applicant") val applicant: String = "",
    @SerializedName("status") val status: String = "Granted",
    @SerializedName("filing_date") val filingDate: String? = null,
    @SerializedName("jurisdiction") val jurisdiction: String = "India",
    @SerializedName("ipc_class") val ipcClass: String? = null,
    @SerializedName("abstract") val abstract: String? = null
)

data class BotanicalInfo(
    @SerializedName("name") val name: String = "",
    @SerializedName("scientific_name") val scientificName: String = "",
    @SerializedName("traditional_uses") val traditionalUses: String = "",
    @SerializedName("classical_texts") val classicalTexts: String = "",
    @SerializedName("sec_3p_risk") val sec3pRisk: String = ""
)

data class PriorArtSearchRequest(
    @SerializedName("query") val query: String
)

data class PriorArtSearchResponse(
    @SerializedName("query") val query: String = "",
    @SerializedName("total_found") val totalFound: Int = 0,
    @SerializedName("detected_botanicals") val detectedBotanicals: List<BotanicalInfo> = emptyList(),
    @SerializedName("patents") val patents: List<PatentRecord> = emptyList(),
    @SerializedName("patentability_barriers") val patentabilityBarriers: List<Map<String, String>> = emptyList(),
    @SerializedName("conclusion_status") val conclusionStatus: String = "",
    @SerializedName("disclaimer") val disclaimer: String = ""
)

data class ComplianceReportResponse(
    @SerializedName("success") val success: Boolean = true,
    @SerializedName("investigation_id") val investigationId: String = "",
    @SerializedName("compliance_summary") val complianceSummary: List<String> = emptyList(),
    @SerializedName("mandatory_forms") val mandatoryForms: List<String> = emptyList(),
    @SerializedName("statutory_triggers") val statutoryTriggers: List<Map<String, String>> = emptyList(),
    @SerializedName("html_report") val htmlReport: String = "",
    @SerializedName("view_url") val viewUrl: String = ""
)

data class RegulationUpdate(
    @SerializedName("id") val id: String? = null,
    @SerializedName("source_name") val sourceName: String = "",
    @SerializedName("title") val title: String = "",
    @SerializedName("notification_number") val notificationNumber: String = "",
    @SerializedName("category") val category: String = "",
    @SerializedName("summary") val summary: String = "",
    @SerializedName("source_url") val sourceUrl: String = "",
    @SerializedName("issued_date") val issuedDate: String = "",
    @SerializedName("status") val status: String = "In Force"
)

data class BotanicalHerb(
    @SerializedName("id") val id: String = "",
    @SerializedName("canonical_name") val canonicalName: String = "",
    @SerializedName("sanskrit_name") val sanskritName: String = "",
    @SerializedName("botanical_name") val botanicalName: String = "",
    @SerializedName("active_actives") val activeActives: String = "",
    @SerializedName("classical_category") val classicalCategory: String = "",
    @SerializedName("emoji") val emoji: String = "🌿"
)

data class CraftCombineRequest(
    @SerializedName("ingredients") val ingredients: List<String>
)

data class CraftCombineResponse(
    @SerializedName("discovered") val discovered: Boolean = true,
    @SerializedName("title") val title: String = "",
    @SerializedName("sanskrit_name") val sanskritName: String? = null,
    @SerializedName("ingredients") val ingredients: List<String> = emptyList(),
    @SerializedName("status") val status: String = "",
    @SerializedName("classical_source") val classicalSource: String? = null,
    @SerializedName("tkdl_status") val tkdlStatus: String = "",
    @SerializedName("patentability_risk_pct") val patentabilityRiskPct: Int = 0,
    @SerializedName("synergy_score_pct") val synergyScorePct: Int = 0,
    @SerializedName("therapeutic_category") val therapeuticCategory: String = "",
    @SerializedName("statutory_rationale") val statutoryRationale: String = "",
    @SerializedName("statutory_requirements") val statutoryRequirements: List<String> = emptyList(),
    @SerializedName("suggested_queries") val suggestedQueries: List<String> = emptyList()
)

// ==========================================================
// REGULATORY GUIDANCE & CLASSIFICATION MODELS
// ==========================================================

data class RegulatoryGuidanceInput(
    val productName: String = "",
    val productType: String = "Ayurvedic Herbal Formulation",
    val ingredients: List<String> = emptyList(),
    val dosageForm: String = "Tablet / Vati",
    val intendedUse: String = "",
    val claims: String = "",
    val manufacturingCountry: String = "India",
    val targetMarkets: List<String> = listOf("India"),
    val manufacturerType: String = "AYUSH Startup",
    val existingLicences: String = "",
    val supportingDocuments: String = ""
)

data class ProductClassification(
    @SerializedName("potential_category") val potentialCategory: String = "Ayurvedic Medicine",
    @SerializedName("confidence_score") val confidenceScore: Float = 0.88f,
    @SerializedName("legal_reasoning") val legalReasoning: String = "",
    @SerializedName("statutory_basis") val statutoryBasis: String = "",
    @SerializedName("authority") val authority: String = "State Ayush Licensing Authority (SLA)",
    @SerializedName("governing_rules") val governingRules: String = "Drugs & Cosmetics Act, 1940 (Rule 158B)",
    @SerializedName("unresolved_questions") val unresolvedQuestions: List<String> = emptyList(),
    @SerializedName("requires_expert_verification") val requiresExpertVerification: Boolean = false
)

data class RegulatoryRequirement(
    @SerializedName("id") val id: String = "",
    @SerializedName("category") val category: String = "Licensing", // Licensing, GMP, Safety, Labelling, Claims, Export/ABS
    @SerializedName("title") val title: String = "",
    @SerializedName("description") val description: String = "",
    @SerializedName("status") val status: String = "needs_verification", // complete, needs_verification, missing, not_applicable, insufficient_evidence
    @SerializedName("authority") val authority: String = "",
    @SerializedName("source_document") val sourceDocument: String = "",
    @SerializedName("section") val section: String? = null,
    @SerializedName("publication_date") val publicationDate: String? = null,
    @SerializedName("confidence") val confidence: Float = 0.92f,
    @SerializedName("evidence_passage") val evidencePassage: String = "",
    @SerializedName("what_user_should_do_next") val whatUserShouldDoNext: String = "",
    @SerializedName("source_url") val sourceUrl: String? = null
)

data class TrustReliabilityReport(
    @SerializedName("evidence_found") val evidenceFound: Boolean = true,
    @SerializedName("authoritative_source_verified") val authoritativeSourceVerified: Boolean = true,
    @SerializedName("source_freshness_verified") val sourceFreshnessVerified: Boolean = true,
    @SerializedName("conflicting_sources_count") val conflictingSourcesCount: Int = 0,
    @SerializedName("retrieval_confidence") val retrievalConfidence: Float = 0.94f,
    @SerializedName("evidence_coverage") val evidenceCoverage: Float = 0.89f,
    @SerializedName("answer_confidence") val answerConfidence: Float = 0.91f,
    @SerializedName("safe_abstention_triggered") val safeAbstentionTriggered: Boolean = false,
    @SerializedName("abstention_reason") val abstentionReason: String? = null,
    @SerializedName("human_escalation_recommended") val humanEscalationRecommended: Boolean = false,
    @SerializedName("escalation_notes") val escalationNotes: String? = null
)

data class RegulatoryGuidanceResponse(
    @SerializedName("id") val id: String = "",
    @SerializedName("product_name") val productName: String = "",
    @SerializedName("classification") val classification: ProductClassification = ProductClassification(),
    @SerializedName("checklist_items") val checklistItems: List<RegulatoryRequirement> = emptyList(),
    @SerializedName("checklist_completion_pct") val checklistCompletionPct: Int = 0,
    @SerializedName("roadmap_steps") val roadmapSteps: List<RoadmapStep> = emptyList(),
    @SerializedName("statutory_risks") val statutoryRisks: List<String> = emptyList(),
    @SerializedName("missing_information") val missingInformation: List<String> = emptyList(),
    @SerializedName("trust_report") val trustReport: TrustReliabilityReport = TrustReliabilityReport(),
    @SerializedName("disclaimer") val disclaimer: String = "This information is evidence-backed regulatory intelligence and does not constitute formal legal approval or legal advice."
)

// ==========================================================
// CLAIM RISK DETECTOR MODELS
// ==========================================================

data class ClaimRiskItem(
    @SerializedName("claim_text") val claimText: String = "",
    @SerializedName("detected_category") val detectedCategory: String = "Therapeutic Claim",
    @SerializedName("risk_level") val riskLevel: String = "HIGH", // CRITICAL, HIGH, MODERATE, LOW
    @SerializedName("flagged_phrases") val flaggedPhrases: List<String> = emptyList(),
    @SerializedName("statutory_bar") val statutoryBar: String = "",
    @SerializedName("governing_authority") val governingAuthority: String = "",
    @SerializedName("evidence_reasoning") val evidenceReasoning: String = "",
    @SerializedName("evidence_needed_to_support") val evidenceNeededToSupport: String = "",
    @SerializedName("recommended_next_action") val recommendedNextAction: String = ""
)

data class ClaimRiskResponse(
    @SerializedName("overall_risk_level") val overallRiskLevel: String = "HIGH",
    @SerializedName("total_claims_analyzed") val totalClaimsAnalyzed: Int = 0,
    @SerializedName("items") val items: List<ClaimRiskItem> = emptyList(),
    @SerializedName("general_advisory") val generalAdvisory: String = "",
    @SerializedName("statutory_sources") val statutorySources: List<SourceItem> = emptyList()
)

// ==========================================================
// LABEL COMPLIANCE MODELS
// ==========================================================

data class LabelItem(
    @SerializedName("field_name") val fieldName: String = "",
    @SerializedName("status") val status: String = "needs_verification", // detected, needs_verification, missing, unable_to_determine
    @SerializedName("detected_value") val detectedValue: String? = null,
    @SerializedName("statutory_requirement") val statutoryRequirement: String = "",
    @SerializedName("authority") val authority: String = "Ministry of Ayush / State Licensing Authority",
    @SerializedName("governing_rule") val governingRule: String = "Drugs & Cosmetics Rules, 1945 — Rule 161",
    @SerializedName("corrective_action") val correctiveAction: String = ""
)

data class LabelComplianceResponse(
    @SerializedName("product_label_name") val productLabelName: String = "",
    @SerializedName("fields") val fields: List<LabelItem> = emptyList(),
    @SerializedName("compliance_readiness_pct") val complianceReadinessPct: Int = 0,
    @SerializedName("critical_deficiencies") val criticalDeficiencies: List<String> = emptyList(),
    @SerializedName("governing_standards") val governingStandards: List<String> = emptyList()
)

// ==========================================================
// INTERNATIONAL REGULATORY COMPARISON MODELS
// ==========================================================

data class InternationalComparisonDimension(
    @SerializedName("dimension") val dimension: String = "",
    @SerializedName("india_details") val indiaDetails: String = "",
    @SerializedName("usa_details") val usaDetails: String = "",
    @SerializedName("eu_details") val euDetails: String = "",
    @SerializedName("key_differences") val keyDifferences: String = ""
)

data class InternationalComparisonResponse(
    @SerializedName("product_title") val productTitle: String = "",
    @SerializedName("target_category") val targetCategory: String = "",
    @SerializedName("dimensions") val dimensions: List<InternationalComparisonDimension> = emptyList(),
    @SerializedName("export_readiness_alerts") val exportReadinessAlerts: List<String> = emptyList(),
    @SerializedName("country_specific_cautions") val countrySpecificCautions: Map<String, String> = emptyMap()
)

