package com.ipsakti.sahayak.data.model

import com.google.gson.annotations.SerializedName

data class QueryRequest(
    @SerializedName("question") val question: String,
    @SerializedName("mode") val mode: String = "quick",
    @SerializedName("language") val language: String = "en"
)

data class SourceItem(
    @SerializedName("document_name") val documentName: String = "",
    @SerializedName("authority") val authority: String? = null,
    @SerializedName("jurisdiction") val jurisdiction: String? = null,
    @SerializedName("section") val section: String? = null,
    @SerializedName("page") val page: String? = null,
    @SerializedName("version") val version: String? = null,
    @SerializedName("effective_date") val effectiveDate: String? = null,
    @SerializedName("source_url") val sourceUrl: String? = null,
    @SerializedName("content") val content: String? = null
)

data class CitationItem(
    @SerializedName("text") val text: String = "",
    @SerializedName("source_id") val sourceId: String = ""
)

data class EvidenceItem(
    @SerializedName("id") val id: String = "",
    @SerializedName("title") val title: String = "",
    @SerializedName("summary") val summary: String = "",
    @SerializedName("source") val source: SourceItem = SourceItem(),
    @SerializedName("relevance_score") val relevanceScore: Float = 0f
)

data class QueryResponse(
    @SerializedName("answer") val answer: String = "",
    @SerializedName("confidence") val confidence: Float = 0f,
    @SerializedName("evidence") val evidence: List<EvidenceItem> = emptyList(),
    @SerializedName("domains") val domains: List<String> = emptyList(),
    @SerializedName("primary_domain") val primaryDomain: String? = null,
    @SerializedName("risks") val risks: List<String> = emptyList(),
    @SerializedName("actions") val actions: List<String> = emptyList(),
    @SerializedName("citations") val citations: List<CitationItem> = emptyList(),
    @SerializedName("citation_verified") val citationVerified: Boolean = true,
    @SerializedName("abstained") val abstained: Boolean = false,
    @SerializedName("disclaimer") val disclaimer: String = "This information is generated by AI and is for general guidance only. It does not constitute legal advice."
)

data class GraphNode(
    @SerializedName("id") val id: String = "",
    @SerializedName("label") val label: String = "",
    @SerializedName("type") val type: String = ""
)

data class GraphEdge(
    @SerializedName("source") val source: String = "",
    @SerializedName("target") val target: String = "",
    @SerializedName("relation") val relation: String = ""
)

data class EvidenceGraphResponse(
    @SerializedName("nodes") val nodes: List<GraphNode> = emptyList(),
    @SerializedName("edges") val edges: List<GraphEdge> = emptyList()
)

data class RoadmapStep(
    @SerializedName("id") val id: String = "",
    @SerializedName("title") val title: String = "",
    @SerializedName("description") val description: String = "",
    @SerializedName("status") val status: String = "pending",
    @SerializedName("duration") val duration: String? = null
)

data class ComplianceRoadmapResponse(
    @SerializedName("steps") val steps: List<RoadmapStep> = emptyList()
)

data class InvestigationSummary(
    @SerializedName("id") val id: String = "",
    @SerializedName("query") val query: String = "",
    @SerializedName("timestamp") val timestamp: String = "",
    @SerializedName("domain") val domain: String = "",
    @SerializedName("status") val status: String = ""
)

data class InvestigationDetail(
    @SerializedName("id") val id: String = "",
    @SerializedName("query") val query: String = "",
    @SerializedName("timestamp") val timestamp: String = "",
    @SerializedName("domain") val domain: String = "",
    @SerializedName("status") val status: String = "",
    @SerializedName("response") val response: QueryResponse = QueryResponse(),
    @SerializedName("graph") val graph: EvidenceGraphResponse = EvidenceGraphResponse(),
    @SerializedName("roadmap") val roadmap: ComplianceRoadmapResponse = ComplianceRoadmapResponse()
)

data class DashboardStats(
    @SerializedName("total_investigations") val totalInvestigations: Int = 0,
    @SerializedName("active_cases") val activeCases: Int = 0,
    @SerializedName("documents_indexed") val documentsIndexed: Int = 0,
    @SerializedName("risk_alerts") val riskAlerts: Int = 0,
    @SerializedName("recent_activity") val recentActivity: List<Map<String, Any>> = emptyList()
)

data class DocumentUploadResponse(
    @SerializedName("status") val status: String = "",
    @SerializedName("message") val message: String = "",
    @SerializedName("document_id") val documentId: String = "",
    @SerializedName("filename") val filename: String? = null,
    @SerializedName("size") val size: Long? = null,
    @SerializedName("pages") val pages: Int? = null,
    @SerializedName("chunks") val chunks: Int? = null
)

data class DocumentInfo(
    @SerializedName("id") val id: String = "",
    @SerializedName("filename") val filename: String = "",
    @SerializedName("upload_date") val uploadDate: String = "",
    @SerializedName("status") val status: String = "Indexed",
    @SerializedName("size") val size: Long = 0L,
    @SerializedName("pages") val pages: Int = 0,
    @SerializedName("chunks") val chunks: Int = 0
)

data class HealthResponse(
    @SerializedName("status") val status: String = "ok",
    @SerializedName("mode") val mode: String = "demo",
    @SerializedName("version") val version: String = "1.0.0",
    @SerializedName("pipeline_ready") val pipelineReady: Boolean = false
)

data class SuggestedAction(
    @SerializedName("label") val label: String = "",
    @SerializedName("target_screen") val targetScreen: String = "",
    @SerializedName("payload") val payload: String? = null
)

data class ChatMessage(
    @SerializedName("id") val id: String = "",
    @SerializedName("sender") val sender: String = "assistant", // "user" or "assistant"
    @SerializedName("text") val text: String = "",
    @SerializedName("timestamp") val timestamp: String = "",
    @SerializedName("actions") val actions: List<SuggestedAction> = emptyList(),
    @SerializedName("domain") val domain: String? = null,
    @SerializedName("domains") val domains: List<String> = emptyList()
)

data class ChatMessageRequest(
    @SerializedName("message") val message: String,
    @SerializedName("history") val history: List<ChatMessage> = emptyList(),
    @SerializedName("language") val language: String = "en"
)

data class ChatResponse(
    @SerializedName("reply") val reply: String = "",
    @SerializedName("suggested_actions") val suggestedActions: List<SuggestedAction> = emptyList(),
    @SerializedName("references") val references: List<String> = emptyList(),
    @SerializedName("domain") val domain: String? = null,
    @SerializedName("domains") val domains: List<String> = emptyList()
)

data class PatentRecord(
    @SerializedName("patent_number") val patentNumber: String = "",
    @SerializedName("title") val title: String = "",
    @SerializedName("applicant") val applicant: String = "",
    @SerializedName("status") val status: String = "Granted",
    @SerializedName("filing_date") val filingDate: String? = null,
    @SerializedName("jurisdiction") val jurisdiction: String = "India",
    @SerializedName("ipc_class") val ipcClass: String? = null,
    @SerializedName("abstract") val abstract: String? = null
)

data class BotanicalInfo(
    @SerializedName("name") val name: String = "",
    @SerializedName("scientific_name") val scientificName: String = "",
    @SerializedName("traditional_uses") val traditionalUses: String = "",
    @SerializedName("classical_texts") val classicalTexts: String = "",
    @SerializedName("sec_3p_risk") val sec3pRisk: String = ""
)

data class PriorArtSearchRequest(
    @SerializedName("query") val query: String
)

data class PriorArtSearchResponse(
    @SerializedName("query") val query: String = "",
    @SerializedName("total_found") val totalFound: Int = 0,
    @SerializedName("detected_botanicals") val detectedBotanicals: List<BotanicalInfo> = emptyList(),
    @SerializedName("patents") val patents: List<PatentRecord> = emptyList(),
    @SerializedName("patentability_barriers") val patentabilityBarriers: List<Map<String, String>> = emptyList(),
    @SerializedName("conclusion_status") val conclusionStatus: String = "",
    @SerializedName("disclaimer") val disclaimer: String = ""
)
